
import React, { useState, useEffect } from 'react';
import { AppView, Workout } from './types';
import Dashboard from './components/Dashboard';
import Uploader from './components/Uploader';
import History from './components/History';
import Analytics from './components/Analytics';
import DataExport from './components/DataExport';
import Login from './components/Login';
import { 
  ChartBarIcon, 
  ArrowUpTrayIcon, 
  ClockIcon, 
  Square2StackIcon,
  Bars3Icon,
  XMarkIcon,
  TableCellsIcon,
  ArrowRightStartOnRectangleIcon
} from '@heroicons/react/24/outline';
import { auth, db } from './firebase';
import { onAuthStateChanged, User, signOut } from 'firebase/auth';
import { 
  collection, 
  query, 
  orderBy, 
  onSnapshot, 
  addDoc, 
  deleteDoc, 
  doc, 
  setDoc 
} from 'firebase/firestore';

const App: React.FC = () => {
  const [user, setUser] = useState<User | null>(null);
  const [authLoading, setAuthLoading] = useState(true);
  
  const [view, setView] = useState<AppView>('dashboard');
  const [workouts, setWorkouts] = useState<Workout[]>([]);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  // 1. Auth Listener
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
      setUser(currentUser);
      setAuthLoading(false);
    });
    return () => unsubscribe();
  }, []);

  // 2. Data Listener (Firestore)
  useEffect(() => {
    if (!user) {
      setWorkouts([]);
      return;
    }

    // Reference: users/{uid}/workouts
    const q = query(
      collection(db, "users", user.uid, "workouts"), 
      orderBy("date", "desc")
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const fetchedWorkouts: Workout[] = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      } as Workout));
      setWorkouts(fetchedWorkouts);
    }, (error) => {
      console.error("Error fetching workouts:", error);
    });

    return () => unsubscribe();
  }, [user]);

  // Add Workouts to Firestore
  const addWorkouts = async (newWorkouts: Workout[]) => {
    if (!user) return;
    
    // We upload each workout as a separate document
    const batchPromises = newWorkouts.map(async (workout) => {
      // Create a doc ref. We can use the ID generated by the logic or let Firestore gen one.
      // Since our workout IDs are based on timestamps, let's just use them or clean them.
      // Using addDoc is safer for auto-ids, but if we want to ensure uniqueness we can use doc()
      // Let's use addDoc for simplicity, ignoring the temp ID generated in Uploader
      const { id, ...data } = workout;
      await addDoc(collection(db, "users", user.uid, "workouts"), data);
    });

    await Promise.all(batchPromises);
    setView('dashboard');
  };

  // Delete from Firestore
  const deleteWorkout = async (id: string) => {
    if (!user) return;
    try {
      await deleteDoc(doc(db, "users", user.uid, "workouts", id));
    } catch (e) {
      console.error("Error deleting workout:", e);
    }
  };

  const handleSignOut = () => {
    signOut(auth);
  };

  const NavItem = ({ id, label, icon: Icon }: { id: AppView, label: string, icon: any }) => (
    <button
      onClick={() => { setView(id); setIsSidebarOpen(false); }}
      className={`flex items-center space-x-3 px-4 py-3 rounded-xl transition-all w-full text-left ${
        view === id 
        ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' 
        : 'text-slate-400 hover:bg-slate-800 hover:text-white'
      }`}
    >
      <Icon className="w-6 h-6" />
      <span className="font-medium">{label}</span>
    </button>
  );

  if (authLoading) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-blue-600/30 border-t-blue-600 rounded-full animate-spin"></div>
      </div>
    );
  }

  if (!user) {
    return <Login />;
  }

  return (
    <div className="min-h-screen flex bg-slate-950">
      {/* Mobile Header */}
      <div className="lg:hidden fixed top-0 left-0 right-0 bg-slate-900/80 backdrop-blur-md z-40 px-4 py-3 flex items-center justify-between border-b border-slate-800">
        <div className="flex items-center space-x-2">
          <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center font-bold text-white">S</div>
          <span className="font-bold tracking-tight text-xl">StrengthInsight</span>
        </div>
        <button onClick={() => setIsSidebarOpen(!isSidebarOpen)}>
          {isSidebarOpen ? <XMarkIcon className="w-7 h-7" /> : <Bars3Icon className="w-7 h-7" />}
        </button>
      </div>

      {/* Sidebar Navigation */}
      <aside className={`
        fixed inset-y-0 left-0 z-50 w-64 bg-slate-900 border-r border-slate-800 p-6 transform transition-transform duration-300 ease-in-out lg:relative lg:translate-x-0 flex flex-col
        ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'}
      `}>
        <div className="flex items-center space-x-3 mb-12 hidden lg:flex">
          <div className="w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center font-bold text-white text-xl">S</div>
          <span className="font-bold tracking-tight text-2xl">StrengthInsight</span>
        </div>

        <nav className="flex-1 flex flex-col space-y-2">
          <NavItem id="dashboard" label="Overview" icon={Square2StackIcon} />
          <NavItem id="upload" label="Upload Workout" icon={ArrowUpTrayIcon} />
          <NavItem id="history" label="Workout Logs" icon={ClockIcon} />
          <NavItem id="analytics" label="Progression" icon={ChartBarIcon} />
          <div className="pt-4 mt-4 border-t border-slate-800">
             <NavItem id="export" label="Export Data" icon={TableCellsIcon} />
          </div>
        </nav>

        <div className="pt-6 border-t border-slate-800">
          <div className="flex items-center space-x-3 px-4 py-3 mb-2">
            <img src={user.photoURL || ''} alt="Profile" className="w-8 h-8 rounded-full bg-slate-700" />
            <div className="overflow-hidden">
              <p className="text-sm font-bold truncate">{user.displayName}</p>
              <p className="text-xs text-slate-500 truncate">{user.email}</p>
            </div>
          </div>
          <button 
            onClick={handleSignOut}
            className="flex items-center space-x-3 px-4 py-2 text-slate-400 hover:text-red-400 w-full transition-colors text-sm font-medium"
          >
            <ArrowRightStartOnRectangleIcon className="w-5 h-5" />
            <span>Sign Out</span>
          </button>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="flex-1 overflow-y-auto p-4 lg:p-10 pt-20 lg:pt-10">
        <div className="max-w-6xl mx-auto">
          {view === 'dashboard' && <Dashboard workouts={workouts} />}
          {view === 'upload' && <Uploader onWorkoutsExtracted={addWorkouts} />}
          {view === 'history' && <History workouts={workouts} onDelete={deleteWorkout} />}
          {view === 'analytics' && <Analytics workouts={workouts} />}
          {view === 'export' && <DataExport workouts={workouts} />}
        </div>
      </main>

      {/* Mobile Overlay */}
      {isSidebarOpen && (
        <div 
          className="fixed inset-0 bg-black/60 backdrop-blur-sm z-40 lg:hidden"
          onClick={() => setIsSidebarOpen(false)}
        />
      )}
    </div>
  );
};

export default App;
